// AUTO-GENERATED by scripts/vk-to-rust.js — do not hand-edit.
//
// ⚠️ PLACEHOLDER. This is a zero-filled stub so the program compiles before the
// pool trusted setup has been run. It will NOT verify any real proof. Regenerate
// the real key with:
//
//   bash scripts/setup-pool.sh
//
// which compiles circuits/withdraw.circom and overwrites this file.
use groth16_solana::groth16::Groth16Verifyingkey;

// 6 public inputs => vk_ic has 7 entries (one per input + 1).
pub const VERIFYINGKEY_POOL: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 6,
    vk_alpha_g1: [0u8; 64],
    vk_beta_g2: [0u8; 128],
    vk_gamme_g2: [0u8; 128],
    vk_delta_g2: [0u8; 128],
    vk_ic: &[
        [0u8; 64],
        [0u8; 64],
        [0u8; 64],
        [0u8; 64],
        [0u8; 64],
        [0u8; 64],
        [0u8; 64],
    ],
};
