// AUTO-GENERATED — do not hand-edit.
//
// Produce this file from the trusted setup:
//   1. snarkjs zkey export verificationkey credential_final.zkey verification_key.json
//   2. Convert verification_key.json into a `Groth16Verifyingkey` constant using
//      light-protocol's parser, e.g.:
//        npx @lightprotocol/circuit-lib ...   (or the `groth16-solana` example tool)
//   3. Paste the generated constant below.
//
// The constant MUST match the circuit in circuits/credential.circom and the
// NUM_PUBLIC_INPUTS used in lib.rs (4: nullifierHash, merkleRoot,
// externalNullifier, signalHash).

use groth16_solana::groth16::Groth16Verifyingkey;

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 4,
    // vk_alpha_g1, vk_beta_g2, vk_gamme_g2, vk_delta_g2, vk_ic: [...]
    // <-- paste generated bytes here -->
    vk_alpha_g1: [0u8; 64],
    vk_beta_g2: [0u8; 128],
    vk_gamme_g2: [0u8; 128],
    vk_delta_g2: [0u8; 128],
    vk_ic: &[],
};
