// Format a snarkjs proof.json + public.json into the byte layout the on-chain
// verifier expects (identical to packages/sdk/src/zk/prover.ts), emitting a Rust
// test snippet so groth16-solana can be exercised host-side.
//
//   node scripts/format-proof.js circuits/build/proof.json circuits/build/public.json

const fs = require("fs");

const Q =
  21888242871839275222246405745257275088696311157297823662689037894645226208583n;

const proof = JSON.parse(fs.readFileSync(process.argv[2], "utf8"));
const pub = JSON.parse(fs.readFileSync(process.argv[3], "utf8"));

function be32(dec) {
  let v = BigInt(dec);
  const out = new Array(32).fill(0);
  for (let i = 31; i >= 0; i--) {
    out[i] = Number(v & 0xffn);
    v >>= 8n;
  }
  return out;
}

const ax = BigInt(proof.pi_a[0]);
const ay = (Q - (BigInt(proof.pi_a[1]) % Q)) % Q;
const proofA = [...be32(ax), ...be32(ay)];

const proofB = [
  ...be32(proof.pi_b[0][1]), ...be32(proof.pi_b[0][0]),
  ...be32(proof.pi_b[1][1]), ...be32(proof.pi_b[1][0]),
];

const proofC = [...be32(proof.pi_c[0]), ...be32(proof.pi_c[1])];

const arr = (b) => `[${b.join(", ")}]`;
const inputs = pub.map((s) => `    ${arr(be32(s))},`).join("\n");

process.stdout.write(`// AUTO-GENERATED by scripts/format-proof.js
pub const PROOF_A: [u8; 64] = ${arr(proofA)};
pub const PROOF_B: [u8; 128] = ${arr(proofB)};
pub const PROOF_C: [u8; 64] = ${arr(proofC)};
pub const PUBLIC_INPUTS: [[u8; 32]; 4] = [
${inputs}
];
`);
