// Convert snarkjs verification_key.json into the groth16-solana
// `Groth16Verifyingkey` Rust constant.
//
// Encoding matches packages/sdk/src/zk/prover.ts: every field element is 32-byte
// big-endian; G1 = x||y; G2 serializes each Fp2 coordinate as c1||c0 (the same
// swap applied to proof.B). Nothing is negated here — the prover negates A.
//
//   node scripts/vk-to-rust.js verification_key.json > programs/soteria-verifier/src/verifying_key.rs

const fs = require("fs");

const vkPath = process.argv[2] || "verification_key.json";
const vk = JSON.parse(fs.readFileSync(vkPath, "utf8"));

function be32(dec) {
  let v = BigInt(dec);
  const out = new Array(32).fill(0);
  for (let i = 31; i >= 0; i--) {
    out[i] = Number(v & 0xffn);
    v >>= 8n;
  }
  return out;
}

const g1 = (p) => [...be32(p[0]), ...be32(p[1])];
const g2 = (p) => [
  ...be32(p[0][1]), ...be32(p[0][0]),
  ...be32(p[1][1]), ...be32(p[1][0]),
];

const arr = (bytes) => `[${bytes.join(", ")}]`;
const ic = vk.IC.map((p) => `        ${arr(g1(p))},`).join("\n");

process.stdout.write(`// AUTO-GENERATED by scripts/vk-to-rust.js — do not hand-edit.
// Regenerate from the trusted setup (see scripts/setup.sh).
use groth16_solana::groth16::Groth16Verifyingkey;

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: ${vk.nPublic},
    vk_alpha_g1: ${arr(g1(vk.vk_alpha_1))},
    vk_beta_g2: ${arr(g2(vk.vk_beta_2))},
    vk_gamme_g2: ${arr(g2(vk.vk_gamma_2))},
    vk_delta_g2: ${arr(g2(vk.vk_delta_2))},
    vk_ic: &[
${ic}
    ],
};
`);
